name: dm_app
description: DeliveryManager Flutter Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5'

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_datetime_picker_plus: ^2.1.0
  font_awesome_flutter: ^10.3.0
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.6
  json_annotation: ^4.7.0
  mvc_pattern: ^8.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
